# Pure validation and comparison only. This module never calls NetSecurity cmdlets.
Set-StrictMode -Version Latest

function Assert-ExactJsonProperties {
    param([object]$Value, [string[]]$Names, [string]$Label)

    if ($null -eq $Value -or $Value -isnot [pscustomobject]) {
        throw "$Label must be a JSON object."
    }
    $actual = @($Value.PSObject.Properties.Name)
    if ($actual.Count -ne $Names.Count) { throw "$Label has unsupported fields." }
    foreach ($name in $Names) {
        if ($actual -cnotcontains $name) { throw "$Label is missing or misnames $name." }
    }
}

function Assert-ScalarString {
    param([object]$Value, [string]$Label)

    if ($Value -isnot [string] -or [string]::IsNullOrWhiteSpace($Value) -or
        $Value.Length -gt 2048 -or $Value -match '[\x00-\x1f]') {
        throw "$Label must be a bounded nonempty string."
    }
}

function Assert-ReviewedRoot {
    param([string]$Root)

    Assert-ScalarString $Root 'ReviewedRoot'
    if ($Root -cnotmatch '^[A-Za-z]:\\' -or $Root.EndsWith('\') -or
        $Root -cnotmatch '^[A-Za-z]:\\[A-Za-z0-9._ -]+(?:\\[A-Za-z0-9._ -]+)*$') {
        throw "ReviewedRoot is not a literal local Windows directory: $Root"
    }
    $segments = $Root.Substring(3).Split('\')
    foreach ($segment in $segments) {
        if ($segment -eq '.' -or $segment -eq '..' -or $segment.EndsWith('.') -or
            $segment.EndsWith(' ')) {
            throw "ReviewedRoot contains an ambiguous path segment: $Root"
        }
    }
    $repository = [string]::Equals($segments[-1], 'TogetherServer',
        [StringComparison]::OrdinalIgnoreCase)
    $worktree = $segments.Count -ge 2 -and
        [string]::Equals($segments[-2], 'TogetherServer-worktrees',
            [StringComparison]::OrdinalIgnoreCase) -and
        $segments[-1] -match '^[A-Za-z0-9][A-Za-z0-9._-]*$'
    if (-not ($repository -or $worktree)) {
        throw "ReviewedRoot must be the TogetherServer repository or one exact worktree: $Root"
    }
}

function Assert-ReviewedRoots {
    param([string[]]$Roots)

    if ($null -eq $Roots -or $Roots.Count -lt 1 -or $Roots.Count -gt 64) {
        throw 'Supply 1 through 64 exact reviewed repository/worktree roots.'
    }
    $seen = @{}
    foreach ($root in $Roots) {
        Assert-ReviewedRoot $root
        if ($seen.ContainsKey($root)) { throw "Duplicate ReviewedRoot: $root" }
        $seen[$root] = $true
    }
}

function Assert-RuleFields {
    param([object]$Record, [string]$Label)

    $fields = @('Name', 'DisplayName', 'Program', 'Enabled', 'Profile', 'Direction', 'Action')
    Assert-ExactJsonProperties $Record $fields $Label
    foreach ($field in $fields) {
        Assert-ScalarString $Record.$field "$Label.$field"
    }
    if ($Record.Enabled -cne 'True' -or $Record.Profile -cne 'Public' -or
        $Record.Direction -cne 'Inbound' -or $Record.Action -cne 'Allow') {
        throw "$Label is not an enabled Public inbound Allow rule."
    }
}

function Assert-AutoGeneratedName {
    param([object]$Record, [string]$Label)

    $guid = '[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}'
    $pattern = '\A(?:TCP|UDP) Query User\{' + $guid + '\}' +
        [regex]::Escape($Record.Program) + '\z'
    if (-not [regex]::IsMatch($Record.Name, $pattern,
            [Text.RegularExpressions.RegexOptions]::CultureInvariant)) {
        throw "$Label.Name is not the exact auto-generated protocol/GUID/Program name."
    }
}

function Assert-HistoricalCheckRule {
    param([object]$Record, [string[]]$ReviewedRoots, [string]$Label = 'Rule')

    Assert-RuleFields $Record $Label
    foreach ($field in @('Name', 'DisplayName', 'Program')) {
        if ($Record.$field -match '(?i)TogetherServer\.exe') {
            throw "$Label references the production TogetherServer.exe."
        }
    }
    $runner = $null
    foreach ($root in $ReviewedRoots) {
        $prefix = $root + '\checks\'
        if (-not $Record.Program.StartsWith($prefix, [StringComparison]::OrdinalIgnoreCase)) {
            continue
        }
        $suffix = $Record.Program.Substring($prefix.Length)
        $match = [regex]::Match($suffix,
            '\A(?<runner>TogetherServer\.Checks|TogetherServer\.CompanionChecks)\\bin\\(?:Debug|Release)\\net10\.0(?:-windows)?\\(?<exe>TogetherServer\.Checks|TogetherServer\.CompanionChecks)\.exe\z',
            [Text.RegularExpressions.RegexOptions]::IgnoreCase -bor
            [Text.RegularExpressions.RegexOptions]::CultureInvariant)
        if ($match.Success -and [string]::Equals($match.Groups['runner'].Value,
                $match.Groups['exe'].Value, [StringComparison]::OrdinalIgnoreCase)) {
            if ([string]::Equals($match.Groups['runner'].Value, 'TogetherServer.Checks',
                    [StringComparison]::OrdinalIgnoreCase)) {
                $runner = 'TogetherServer.Checks'
            }
            else { $runner = 'TogetherServer.CompanionChecks' }
            break
        }
    }
    if ($null -eq $runner -or $Record.DisplayName -cne $runner) {
        throw "$Label is not a check-runner executable under an exact reviewed root."
    }
    Assert-AutoGeneratedName $Record $Label
}

function Assert-CurrentReleaseRule {
    param([object]$Record, [string]$Label)

    Assert-RuleFields $Record $Label
    if ($Record.DisplayName -cne 'TogetherServer' -or
        $Record.Program -notmatch '(?i)\\local-data\\release\\TogetherServer\.exe\z') {
        throw "$Label is not an expected protected release rule."
    }
    Assert-AutoGeneratedName $Record $Label
}

function Assert-ReviewedInventory {
    param([object]$Inventory, [string[]]$ReviewedRoots)

    Assert-ReviewedRoots $ReviewedRoots
    Assert-ExactJsonProperties $Inventory @('Schema', 'CapturedUtc', 'PolicyStore',
        'HistoricalCheckRunnerRules', 'CurrentReleaseRules') 'Inventory'
    if ($Inventory.Schema -isnot [int] -or $Inventory.Schema -ne 1 -or
        $Inventory.PolicyStore -isnot [string] -or
        $Inventory.PolicyStore -cne 'PersistentStore') {
        throw 'Inventory must have schema 1 and PolicyStore PersistentStore.'
    }
    Assert-ScalarString $Inventory.CapturedUtc 'Inventory.CapturedUtc'
    if ($Inventory.CapturedUtc -notmatch '^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?Z$') {
        throw 'Inventory.CapturedUtc must be a UTC timestamp.'
    }
    $timestamp = [datetimeoffset]::MinValue
    if (-not [datetimeoffset]::TryParse($Inventory.CapturedUtc, [ref]$timestamp)) {
        throw 'Inventory.CapturedUtc is invalid.'
    }
    if ($Inventory.HistoricalCheckRunnerRules -isnot [array] -or
        $Inventory.HistoricalCheckRunnerRules.Count -lt 1 -or
        $Inventory.HistoricalCheckRunnerRules.Count -gt 128 -or
        $Inventory.CurrentReleaseRules -isnot [array] -or
        $Inventory.CurrentReleaseRules.Count -gt 32) {
        throw 'Inventory rule arrays are missing or outside review bounds.'
    }
    $names = @{}
    $index = 0
    foreach ($record in $Inventory.HistoricalCheckRunnerRules) {
        Assert-HistoricalCheckRule $record $ReviewedRoots "HistoricalCheckRunnerRules[$index]"
        if ($names.ContainsKey($record.Name)) { throw 'Inventory contains duplicate rule names.' }
        $names[$record.Name] = $true
        $index++
    }
    $index = 0
    foreach ($record in $Inventory.CurrentReleaseRules) {
        Assert-CurrentReleaseRule $record "CurrentReleaseRules[$index]"
        if ($names.ContainsKey($record.Name)) {
            throw 'A historical rule overlaps a protected release rule.'
        }
        $names[$record.Name] = $true
        $index++
    }
}

function Read-ReviewedInventory {
    param([string]$InventoryPath, [string[]]$ReviewedRoots, [ref]$Sha256)

    Assert-ScalarString $InventoryPath 'InventoryPath'
    $file = Get-Item -LiteralPath $InventoryPath -ErrorAction Stop
    if ($file -isnot [IO.FileInfo] -or $file.Extension -cne '.json' -or
        $file.Length -lt 1 -or $file.Length -gt 1MB -or
        ($file.Attributes -band [IO.FileAttributes]::ReparsePoint)) {
        throw 'Inventory must be a regular JSON file of at most 1 MiB.'
    }
    try {
        # The digest and JSON must come from one bounded, exclusively opened byte
        # buffer. Hashing the path before or after a separate read would not bind
        # the owner's reviewed digest to the rules parsed below.
        $stream = [IO.FileStream]::new($file.FullName, [IO.FileMode]::Open,
            [IO.FileAccess]::Read, [IO.FileShare]::None)
        try {
            if ($stream.Length -lt 1 -or $stream.Length -gt 1MB) {
                throw 'Inventory size changed while being opened.'
            }
            $bytes = [byte[]]::new([int]$stream.Length)
            $offset = 0
            while ($offset -lt $bytes.Length) {
                $count = $stream.Read($bytes, $offset, $bytes.Length - $offset)
                if ($count -le 0) { throw 'Inventory ended while being read.' }
                $offset += $count
            }
            if ($stream.ReadByte() -ne -1) { throw 'Inventory grew while being read.' }
        }
        finally { $stream.Dispose() }

        $hasher = [Security.Cryptography.SHA256]::Create()
        try { $digest = [BitConverter]::ToString($hasher.ComputeHash($bytes)).Replace('-', '') }
        finally { $hasher.Dispose() }
        $utf8 = New-Object Text.UTF8Encoding($false, $true)
        $raw = $utf8.GetString($bytes)
        if ($raw.Length -gt 0 -and $raw[0] -eq [char]0xFEFF) {
            $raw = $raw.Substring(1)
        }
        $inventory = $raw | ConvertFrom-Json -ErrorAction Stop
    }
    catch { throw 'Inventory is not valid JSON.' }
    Assert-ReviewedInventory $inventory $ReviewedRoots
    # Windows PowerShell 5.1 keeps the last value of a repeated JSON key. Require
    # exactly one textual occurrence of every schema key per expected object.
    $recordCount = $inventory.HistoricalCheckRunnerRules.Count +
        $inventory.CurrentReleaseRules.Count
    foreach ($field in @('Schema', 'CapturedUtc', 'PolicyStore',
            'HistoricalCheckRunnerRules', 'CurrentReleaseRules')) {
        $pattern = '(?<!\\)"' + [regex]::Escape($field) + '"\s*:'
        if ([regex]::Matches($raw, $pattern).Count -ne 1) {
            throw "Inventory has an ambiguous or encoded $field key."
        }
    }
    foreach ($field in @('Name', 'DisplayName', 'Program', 'Enabled',
            'Profile', 'Direction', 'Action')) {
        $pattern = '(?<!\\)"' + [regex]::Escape($field) + '"\s*:'
        if ([regex]::Matches($raw, $pattern).Count -ne $recordCount) {
            throw "Inventory has ambiguous or encoded $field keys."
        }
    }
    if ($null -ne $Sha256) { $Sha256.Value = $digest }
    return $inventory
}

function Get-ReviewedRuleDecision {
    param([object]$ReviewedRecord, [object[]]$LiveRules,
        [object[]]$ApplicationFilters)

    if ($null -eq $LiveRules -or $LiveRules.Count -ne 1) {
        throw 'Live rule is missing or ambiguous.'
    }
    if ($null -eq $ApplicationFilters -or $ApplicationFilters.Count -ne 1) {
        throw 'Live application filter is missing or ambiguous.'
    }
    $live = $LiveRules[0]
    $filter = $ApplicationFilters[0]
    if ($null -eq $live -or $null -eq $filter) { throw 'Live rule/filter is null.' }
    foreach ($field in @('Name', 'DisplayName', 'Enabled', 'Profile', 'Direction',
            'Action', 'PolicyStoreSource')) {
        $property = $live.PSObject.Properties[$field]
        if ($null -eq $property -or $null -eq $property.Value -or
            $property.Value -is [array] -or $property.Value -is [pscustomobject]) {
            throw "Live rule has unsupported $field."
        }
    }
    $programProperty = $filter.PSObject.Properties['Program']
    if ($null -eq $programProperty -or $programProperty.Value -isnot [string]) {
        throw 'Live application filter has unsupported Program.'
    }
    foreach ($field in @('Name', 'DisplayName', 'Enabled', 'Profile',
            'Direction', 'Action')) {
        if (-not [string]::Equals([string]$live.$field, [string]$ReviewedRecord.$field,
                [StringComparison]::Ordinal)) {
            throw "Live rule $field changed from the reviewed inventory."
        }
    }
    if (-not [string]::Equals([string]$live.PolicyStoreSource, 'PersistentStore',
            [StringComparison]::Ordinal)) {
        throw 'Live rule is not sourced from PersistentStore.'
    }
    foreach ($value in @([string]$live.Name, [string]$live.DisplayName,
            [string]$programProperty.Value)) {
        if ($value -match '(?i)TogetherServer\.exe') {
            throw 'Live rule references the production TogetherServer.exe.'
        }
    }
    if (-not [string]::Equals($programProperty.Value, $ReviewedRecord.Program,
            [StringComparison]::Ordinal)) {
        throw 'Live application Program changed from the reviewed inventory.'
    }
    return [pscustomobject]@{
        Decision = 'WouldRemoveExactRule'
        Name = $ReviewedRecord.Name
        Program = $ReviewedRecord.Program
    }
}

Export-ModuleMember -Function Assert-ReviewedRoots, Assert-HistoricalCheckRule,
    Assert-ReviewedInventory, Read-ReviewedInventory, Get-ReviewedRuleDecision
